### ISSUE TITLE
Reusing the same TypeReference instance breaks reference resolution in the current master

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1216]
There's a difference in the type reference resolution logic between 10.0 release and the current master.
If the exact same `TypeReference` instances is used in multiple places, it will not work correctly in master.

```java
GraphQLTypeReference ref = new GraphQLTypeReference("String");

GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(GraphQLObjectType.newObject()
                        .name("Query")
                        .field(GraphQLFieldDefinition.newFieldDefinition()
                                .name("test")
                                .type(Scalars.GraphQLString)
                                .argument(GraphQLArgument.newArgument()
                                        .name("in")
                                        .type(GraphQLInputObjectType.newInputObject()
                                                .name("ObjInput")
                                                .field(GraphQLInputObjectField.newInputObjectField()
                                                        .name("value")
                                                        .type(ref)) //Will get replaced, as expected
                                                .field(GraphQLInputObjectField.newInputObjectField()
                                                        .name("value2")
                                                        .type(ref)) //Will *not* get replaced the 2nd time it's used
                                                .build())
                                )
                                .dataFetcher(env -> "test")
                        )
                )
                .build();
```

I'm guessing it gets marked as visited the first time, so it won't get checked again.

**Comment by kaqqao** [comment]
Seems like this is rather expected side-effect of #1084. Not sure if anything can be done, nor if anything _should_ be done... But it does cause a rather insidious regression that insta-bit me 😩

**Comment by bbakerman** [comment]
Hmmm I think this should be fixed @andimarek - the whole idea of a type reference is re-use and indirection.

I will see what we can do to fix this

**Comment by andimarek** [comment]
yes that should be fixed @bbakerman

**Comment by bbakerman** [comment]
I suspect this might be fixed on master.  I tried this repoduction from the above and it works without error

```
    def "the same reference can be used multiple times"() {
        when:
        GraphQLTypeReference ref = new GraphQLTypeReference("String");
        def inputObject = GraphQLInputObjectType.newInputObject()
                .name("ObjInput")
                .field(GraphQLInputObjectField.newInputObjectField()
                .name("value")
                .type(ref)) //Will get replaced, as expected
                .field(GraphQLInputObjectField.newInputObjectField()
                .name("value2")
                .type(ref)) //Will *not* get replaced the 2nd time it's used
                .build()

        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(GraphQLObjectType.newObject()
                .name("Query")
                .field(GraphQLFieldDefinition.newFieldDefinition()
                .name("test")
                .type(Scalars.GraphQLString)
                .dataFetcher({ env -> "test" })
                .argument(GraphQLArgument.newArgument()
                .name("in")
                .type(inputObject))
        )).build()

        then:
        schema != null
```

It gets replaced as expected.  Is there another case where this might be different.??

I will contribute this test as future protection against regression (since we have done it once apparently)

**Comment by bbakerman** [comment]
I am going to close this as we have proof its working as expected

**Comment by kaqqao** [comment]
This is still broken, the test was just checking the wrong thing. No exceptions get thrown, but the resulting schema is invalid, as a `GraphQLTypeReference` remains unresolved.

As mentioned, this is a side-effect of #1084, because the traverser keeps track of replaced references, and once an instance of `GraphQLTypeReference` is marked as resolved, the same instance will never be handled again. Which results in an invalid schema. Not sure how to approach this, but it's way too insidious to leave it as it is. At least an exception that tells the user what is happening is needed...

**Comment by bbakerman** [comment]
@kaqqao provided a test that proves this is still not working in all cases
