### ISSUE TITLE
[15.0 Regression] Directive values of type 'EnumValue' generate 'No Value present' error

### ISSUE THREAD

**Issue by etienne-sf** [graphql-java/graphql-java#1844]
Hello,

I'm trying to use the below directive, with graphql-java 14.0:
directive @relation(
    name: String
    direction: direction
) on FIELD_DEFINITION

enum direction {
    IN
    OUT
}

type Test  {
    id: ID!
    name: String!  @relation(name: "an id's relation", direction: OUT)
}

But I get this error, when the server starts:
Internal error: should never happen: Directive values of type 'EnumValue' are not supported yet

When will enum be accepted as directive values ?
What about int, float, boolean, custom scalars ?

Etienne

**Comment by andimarek** [comment]
this should be fixed at master. Can you try the latest build? thanks

**Comment by etienne-sf** [comment]
Ok, thanks,

And yes, I can test from the master branch.... with some help.
:)

My other project is a maven one.
I have issues pushing the built graphql-java.jar into the local maven repository.
I successively pushed the jar, but the pom. And there are dependencies.

I think I must also push the pom.
Is there any task for that in the graphql-java gradle build ?

Etienne

**Comment by andimarek** [comment]
you can find informations on how to use the latest build here: https://www.graphql-java.com/documentation/v14/getting-started/ 
we publish every master build to bintray, so normally there is no need to build it yourself.

If you want to do it: `./gradlew publishToMavenLocal` will build and publish into your local maven repo

**Comment by etienne-sf** [comment]
Hello,

  Thanks to your hint, I tried the graphq-java master, with a version I just updated from the git's master.

The error changed, but it still doesn't work.
I no more have the "Directive values of type 'EnumValue' are not supported yet" message.
Instead, "I get a java.util.NoSuchElementException: No value present" (see below for the full stack trace).

To repeat it, you can check out the  _**Issue_35_1844**_ branch on this repo:
git@github.com:graphql-java-generator/graphql-maven-plugin-project.git

Do a full maven build (_mvn build install_). The build will hang:
- In the tests for _graphql-maven-plugin-samples-allGraphQLCases-client_
- When it tries to start the server created in the module _graphql-maven-plugin-samples-allGraphQLCases-server_.

To directly execute/debug the _graphql-maven-plugin-samples-allGraphQLCases-server_, you can start the _GraphQLServerMain_ class, generated in:
- The graphql-maven-plugin-samples\graphql-maven-plugin-samples-allGraphQLCases-server\target\generated-sources\graphql-maven-plugin folder
- Then in the org.allGraphQLCases.server package


The error stack trace is:

10:02:38.726 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLProvider': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.allGraphQLCases.server.GraphQLServerMain.main(GraphQLServerMain.java:21) [classes/:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:141) ~[?:?]
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirective(SchemaGeneratorHelper.java:172) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.buildDirectives(SchemaGenerator.java:922) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.buildEnumValue(SchemaGenerator.java:672) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.lambda$buildEnumType$17(SchemaGenerator.java:631) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
	at graphql.schema.idl.SchemaGenerator.buildEnumType(SchemaGenerator.java:630) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.buildInputType(SchemaGenerator.java:465) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalDirectives$2(SchemaGenerator.java:391) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveArgumentFromDefinition(SchemaGeneratorHelper.java:251) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildDirectiveFromDefinition$7(SchemaGeneratorHelper.java:240) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveFromDefinition(SchemaGeneratorHelper.java:241) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalDirectives$3(SchemaGenerator.java:392) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[?:?]
	at graphql.schema.idl.SchemaGenerator.buildAdditionalDirectives(SchemaGenerator.java:390) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:259) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:252) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:222) ~[graphql-java-2020-04-06T09-53-52-9eae9c1b.jar:?]
	at org.allGraphQLCases.server.GraphQLProvider.buildSchema(GraphQLProvider.java:116) ~[classes/:?]
	at org.allGraphQLCases.server.GraphQLProvider.init(GraphQLProvider.java:108) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	... 18 more

**Comment by andimarek** [comment]
hi @etienne-sf: Is this still a problem?
If yes it would be great if you can produce a simple test in graphql java which shows this error. This would help us a lot to tackle this issue. thanks

**Comment by etienne-sf** [comment]
Hello,

I just created this repository for you to repeat this issue:

https://github.com/etienne-sf/graphql-java-issue-1844

You can execute this sample by executing the **_org.allGraphQLCases.server.GraphQLServerMain_** class.

In the current pom, the graphql-java version is set to 14.0.
So you can repeat the "starting" issue (_Internal error: should never happen: Directive values of type 'EnumValue' are not supported yet_).

On line 284 of the pom, you can change the graphql-java version.

When I switch to the just updated and compiled graphql-java, the error becomes: _No value present_

Hope this helps.

Etienne

**Comment by andimarek** [comment]
Sorry I was not perfectly clear, but with a simple test in GraphQL Java I meant a simple unit test. This is the best way to isolate the problem: you current project contains a lot of other code and a lot of dependencies on other libraries on top of GraphQL Java and it is hard to say where the problem comes from without understanding the whole code base.

But I looked again at the stacktrace and I noticed that the exception is thrown inside a function which tries to get the directive definition for a certain directive. I would recommend to look into whether you are using some undeclared directive somewhere.

**Comment by etienne-sf** [comment]
Yep, logical.

I created the junit test testCase1 and testCase2, that fail, due to the issue above.
They go respectively with the GraphQL schema testCase1.graphqls and testCase2.graphqls (in /src/test/resources).

Is that what you were asking ?
Or do you want a PR on graphql-java, with these failing tests ?
If yes, tell me where to put them.

The reason seems to be that a Directive is applied on an enum (testCase1) or a custom scalar (testCase2).
They work with graphql-java v14.0.
But not with the graphql-java's version I checked out some days ago

I created testCase3 and testCaseFull to search for other failing cases. But I didn't find others.

Etienne

**Comment by etienne-sf** [comment]
I close this issue, and will create more precise ones, as this thread is actually unreadable.

Sorry for that.
